USE panama;
CREATE TABLE `panamapreview` (
`DESCRIPCION` VARCHAR(100),
`MERCADO` VARCHAR(50),
`CILINDRADA` float,
`SEGMENTO.1` VARCHAR(50),
`MARCA` VARCHAR(50),
`CILINDROS.1` float,
`MODELO` VARCHAR(50),
`NUMERO CHASIS / VIN` VARCHAR(50),
`CILINDROS` VARCHAR(50)
);
