USE colombia;
CREATE TABLE `motocicletas2` (
`CLASE` VARCHAR(50),
`MARCA` VARCHAR(50),
`LINEA` VARCHAR(50),
`AÑO` int,
`TIPO_SERVICIO` VARCHAR(50),
`TIPO_CARROCERIA` VARCHAR(50),
`CILINDRAJE` FLOAT,
`DEPARTAMENTO` VARCHAR(50),
`MUNICIPIO` VARCHAR(50),
`IMPORTACION` VARCHAR(50),
`CANTIDAD_EJES` int,
`CAPACIDAD_CARGA` int,
`TIPO_COMBUSTIBLE` VARCHAR(50),
`MOTOR` VARCHAR(50),
`SERIE` VARCHAR(50),
`VIN` VARCHAR(50),
`CANTIDAD` int,
`ORIGEN` VARCHAR(50)
);
