USE colombia;
LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaentregar\\MOTOCICLETAS-COLOMBIA\\cuadriciclo.csv" INTO TABLE motocicletas
CHARACTER SET latin1
FIELDS TERMINATED BY "," ENCLOSED BY '"'  ENCLOSED BY '"' 
LINES TERMINATED BY "\n"
IGNORE 1 LINES
(`CLASE`,`MARCA`, `LINEA`,`AÑO`,`TIPO_SERVICIO`,
`TIPO_CARROCERIA`, `CILINDRAJE`, `DEPARTAMENTO`, `MUNICIPIO`,
`IMPORTACION`, `CANTIDAD_EJES`, `CAPACIDAD_CARGA`, `TIPO_COMBUSTIBLE`,
`MOTOR`, `SERIE`, `VIN`, `CANTIDAD`, `ORIGEN`
);

LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaentregar\\MOTOCICLETAS-COLOMBIA\\cuatrimoto.csv" INTO TABLE motocicletas
CHARACTER SET latin1
FIELDS TERMINATED BY "," ENCLOSED BY '"' 
LINES TERMINATED BY "\n"
IGNORE 1 LINES
(`CLASE`,`MARCA`, `LINEA`,`AÑO`,`TIPO_SERVICIO`,
`TIPO_CARROCERIA`, `CILINDRAJE`, `DEPARTAMENTO`, `MUNICIPIO`,
`IMPORTACION`, `CANTIDAD_EJES`, `CAPACIDAD_CARGA`, `TIPO_COMBUSTIBLE`,
`MOTOR`, `SERIE`, `VIN`, `CANTIDAD`, `ORIGEN`
);

LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaentregar\\MOTOCICLETAS-COLOMBIA\\motocarro.csv" INTO TABLE motocicletas
CHARACTER SET latin1
FIELDS TERMINATED BY "," ENCLOSED BY '"' 
LINES TERMINATED BY "\n"
IGNORE 1 LINES
(`CLASE`,`MARCA`, `LINEA`,`AÑO`,`TIPO_SERVICIO`,
`TIPO_CARROCERIA`, `CILINDRAJE`, `DEPARTAMENTO`, `MUNICIPIO`,
`IMPORTACION`, `CANTIDAD_EJES`, `CAPACIDAD_CARGA`, `TIPO_COMBUSTIBLE`,
`MOTOR`, `SERIE`, `VIN`, `CANTIDAD`, `ORIGEN`
);

LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaentregar\\MOTOCICLETAS-COLOMBIA\\motocicleta_p1.csv" INTO TABLE motocicletas
CHARACTER SET latin1
FIELDS TERMINATED BY "," ENCLOSED BY '"' 
LINES TERMINATED BY "\n"
IGNORE 1 LINES
(`CLASE`,`MARCA`, `LINEA`,`AÑO`,`TIPO_SERVICIO`,
`TIPO_CARROCERIA`, `CILINDRAJE`, `DEPARTAMENTO`, `MUNICIPIO`,
`IMPORTACION`, `CANTIDAD_EJES`, `CAPACIDAD_CARGA`, `TIPO_COMBUSTIBLE`,
`MOTOR`, `SERIE`, `VIN`, `CANTIDAD`, `ORIGEN`
);

LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaentregar\\MOTOCICLETAS-COLOMBIA\\motocicleta_p2.csv" INTO TABLE motocicletas
CHARACTER SET latin1
FIELDS TERMINATED BY "," ENCLOSED BY '"' 
LINES TERMINATED BY "\n"
IGNORE 1 LINES
(`CLASE`,`MARCA`, `LINEA`,`AÑO`,`TIPO_SERVICIO`,
`TIPO_CARROCERIA`, `CILINDRAJE`, `DEPARTAMENTO`, `MUNICIPIO`,
`IMPORTACION`, `CANTIDAD_EJES`, `CAPACIDAD_CARGA`, `TIPO_COMBUSTIBLE`,
`MOTOR`, `SERIE`, `VIN`, `CANTIDAD`, `ORIGEN`
);

LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaentregar\\MOTOCICLETAS-COLOMBIA\\motocicleta_p3.csv" INTO TABLE motocicletas
CHARACTER SET latin1
FIELDS TERMINATED BY "," ENCLOSED BY '"' 
LINES TERMINATED BY "\n"
IGNORE 1 LINES
(`CLASE`,`MARCA`, `LINEA`,`AÑO`,`TIPO_SERVICIO`,
`TIPO_CARROCERIA`, `CILINDRAJE`, `DEPARTAMENTO`, `MUNICIPIO`,
`IMPORTACION`, `CANTIDAD_EJES`, `CAPACIDAD_CARGA`, `TIPO_COMBUSTIBLE`,
`MOTOR`, `SERIE`, `VIN`, `CANTIDAD`, `ORIGEN`
);

LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaentregar\\MOTOCICLETAS-COLOMBIA\\motocicleta_p4.csv" INTO TABLE motocicletas
CHARACTER SET latin1
FIELDS TERMINATED BY "," ENCLOSED BY '"' 
LINES TERMINATED BY "\n"
IGNORE 1 LINES
(`CLASE`,`MARCA`, `LINEA`,`AÑO`,`TIPO_SERVICIO`,
`TIPO_CARROCERIA`, `CILINDRAJE`, `DEPARTAMENTO`, `MUNICIPIO`,
`IMPORTACION`, `CANTIDAD_EJES`, `CAPACIDAD_CARGA`, `TIPO_COMBUSTIBLE`,
`MOTOR`, `SERIE`, `VIN`, `CANTIDAD`, `ORIGEN`
);

LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaentregar\\MOTOCICLETAS-COLOMBIA\\motocicleta_p5.csv" INTO TABLE motocicletas
CHARACTER SET latin1
FIELDS TERMINATED BY "," ENCLOSED BY '"' 
LINES TERMINATED BY "\n"
IGNORE 1 LINES
(`CLASE`,`MARCA`, `LINEA`,`AÑO`,`TIPO_SERVICIO`,
`TIPO_CARROCERIA`, `CILINDRAJE`, `DEPARTAMENTO`, `MUNICIPIO`,
`IMPORTACION`, `CANTIDAD_EJES`, `CAPACIDAD_CARGA`, `TIPO_COMBUSTIBLE`,
`MOTOR`, `SERIE`, `VIN`, `CANTIDAD`, `ORIGEN`
);


LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaentregar\\MOTOCICLETAS-COLOMBIA\\motocicleta_p6.csv" INTO TABLE motocicletas
CHARACTER SET latin1
FIELDS TERMINATED BY "," ENCLOSED BY '"' 
LINES TERMINATED BY "\n"
IGNORE 1 LINES
(`CLASE`,`MARCA`, `LINEA`,`AÑO`,`TIPO_SERVICIO`,
`TIPO_CARROCERIA`, `CILINDRAJE`, `DEPARTAMENTO`, `MUNICIPIO`,
`IMPORTACION`, `CANTIDAD_EJES`, `CAPACIDAD_CARGA`, `TIPO_COMBUSTIBLE`,
`MOTOR`, `SERIE`, `VIN`, `CANTIDAD`, `ORIGEN`
);


LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaentregar\\MOTOCICLETAS-COLOMBIA\\motocicleta_p7.csv" INTO TABLE motocicletas
CHARACTER SET latin1
FIELDS TERMINATED BY "," ENCLOSED BY '"' 
LINES TERMINATED BY "\n"
IGNORE 1 LINES
(`CLASE`,`MARCA`, `LINEA`,`AÑO`,`TIPO_SERVICIO`,
`TIPO_CARROCERIA`, `CILINDRAJE`, `DEPARTAMENTO`, `MUNICIPIO`,
`IMPORTACION`, `CANTIDAD_EJES`, `CAPACIDAD_CARGA`, `TIPO_COMBUSTIBLE`,
`MOTOR`, `SERIE`, `VIN`, `CANTIDAD`, `ORIGEN`
);


LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaentregar\\MOTOCICLETAS-COLOMBIA\\motocicleta_p8.csv" INTO TABLE motocicletas
CHARACTER SET latin1
FIELDS TERMINATED BY "," ENCLOSED BY '"' 
LINES TERMINATED BY "\n"
IGNORE 1 LINES
(`CLASE`,`MARCA`, `LINEA`,`AÑO`,`TIPO_SERVICIO`,
`TIPO_CARROCERIA`, `CILINDRAJE`, `DEPARTAMENTO`, `MUNICIPIO`,
`IMPORTACION`, `CANTIDAD_EJES`, `CAPACIDAD_CARGA`, `TIPO_COMBUSTIBLE`,
`MOTOR`, `SERIE`, `VIN`, `CANTIDAD`, `ORIGEN`
);



LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaentregar\\MOTOCICLETAS-COLOMBIA\\motocicleta_p9.csv" INTO TABLE motocicletas
CHARACTER SET latin1
FIELDS TERMINATED BY "," ENCLOSED BY '"' 
LINES TERMINATED BY "\n"
IGNORE 1 LINES
(`CLASE`,`MARCA`, `LINEA`,`AÑO`,`TIPO_SERVICIO`,
`TIPO_CARROCERIA`, `CILINDRAJE`, `DEPARTAMENTO`, `MUNICIPIO`,
`IMPORTACION`, `CANTIDAD_EJES`, `CAPACIDAD_CARGA`, `TIPO_COMBUSTIBLE`,
`MOTOR`, `SERIE`, `VIN`, `CANTIDAD`, `ORIGEN`
);


LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaentregar\\MOTOCICLETAS-COLOMBIA\\motocicleta_p10.csv" INTO TABLE motocicletas
CHARACTER SET latin1
FIELDS TERMINATED BY "," ENCLOSED BY '"' 
LINES TERMINATED BY "\n"
IGNORE 1 LINES
(`CLASE`,`MARCA`, `LINEA`,`AÑO`,`TIPO_SERVICIO`,
`TIPO_CARROCERIA`, `CILINDRAJE`, `DEPARTAMENTO`, `MUNICIPIO`,
`IMPORTACION`, `CANTIDAD_EJES`, `CAPACIDAD_CARGA`, `TIPO_COMBUSTIBLE`,
`MOTOR`, `SERIE`, `VIN`, `CANTIDAD`, `ORIGEN`
);


LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaentregar\\MOTOCICLETAS-COLOMBIA\\mototriciclo.csv" INTO TABLE motocicletas
CHARACTER SET latin1
FIELDS TERMINATED BY "," ENCLOSED BY '"' 
LINES TERMINATED BY "\n"
IGNORE 1 LINES
(`CLASE`,`MARCA`, `LINEA`,`AÑO`,`TIPO_SERVICIO`,
`TIPO_CARROCERIA`, `CILINDRAJE`, `DEPARTAMENTO`, `MUNICIPIO`,
`IMPORTACION`, `CANTIDAD_EJES`, `CAPACIDAD_CARGA`, `TIPO_COMBUSTIBLE`,
`MOTOR`, `SERIE`, `VIN`, `CANTIDAD`, `ORIGEN`
);
