SET GLOBAL local_infile = 1;
USE noschema;
LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaunir\\paraguay.csv" INTO TABLE noschema.flota
FIELDS TERMINATED BY ","
ENCLOSED BY '"'
LINES TERMINATED BY "\r\n"
IGNORE 1 LINES
(`MERCADO`,
`SEGMENTO`,
`MARCA`,
`MGEN`,
`MODELO`,
`COLUMNA REFERENCIA`,
`VERSION (SALES DESCRIPTION)`,
`AÑO`,
`MOTOR`,
`CANTIDAD`,
`ORIGEN`,
`SEGMENTO.1`,
`CARROCERIA`,
`TRACCION`
)