SET GLOBAL local_infile = 1;
USE noschema;
LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaunir\\peru.csv" INTO TABLE noschema.flota
FIELDS TERMINATED BY ","
ENCLOSED BY '"'
LINES TERMINATED BY "\r\n"
IGNORE 1 LINES
(`MERCADO`,
`SEGMENTO`,
`SEGMENTO.1`,
`MARCA`,
`MODELO`,
`COLUMNA REFERENCIA`,
`VERSION (SALES DESCRIPTION)`,
`AÑO`,
`ORIGEN`,
`CARROCERIA`,
`NUMERO CHASIS / VIN`,
`NUMERO MOTOR`,
`COMBUSTIBLE`,
`TRACCION`,
`CILINDRADA`,
`TRANSMISION`,
`MOTOR`,
`CANTIDAD`,
`FECHA ORIGEN`,
`DOCUMENTO ORIGEN`,
`IDENTIFICACION MOTOR`)
;
