SET GLOBAL local_infile = 1;
USE noschema;
LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaunir\\chile_prt.csv" INTO TABLE noschema.flota
FIELDS TERMINATED BY ","
ENCLOSED BY '"'
LINES TERMINATED BY "\r\n"
IGNORE 1 LINES
(`MERCADO`,
`MARCA`,
`MGEN`,
`MODELO`,
`COLUMNA REFERENCIA`,
`VERSION (SALES DESCRIPTION)`,
`AÑO`,
`MOTOR`,
`NUMERO MOTOR`,
`NUMERO CHASIS / VIN`,
`CANTIDAD`,
`ORIGEN`,
`SEGMENTO`,
`SEGMENTO.1`,
`CARROCERIA`,
`TRACCION`,
`CILINDRADA`,
`IDENTIFICACION MOTOR`
);