SET GLOBAL local_infile = 1;
USE noschema;
LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaunir\\peru.csv" INTO TABLE noschema.flota
FIELDS TERMINATED BY ","
ENCLOSED BY '"'
LINES TERMINATED BY "\r\n"
IGNORE 1 LINES
(`MERCADO`,
`SEGMENTO`,
`SEGMENTO.1`,
`MARCA`,
`MODELO`,
`COLUMNA REFERENCIA`,
`VERSION (SALES DESCRIPTION)`,
`AÑO`,
`ORIGEN`,
`CARROCERIA`,
`NUMERO CHASIS / VIN`,
`NUMERO MOTOR`,
`COMBUSTIBLE`,
`TRACCION`,
`CILINDRADA`,
`TRANSMISION`,
`MOTOR`,
`CANTIDAD`,
`FECHA ORIGEN`,
`DOCUMENTO ORIGEN`,
`IDENTIFICACION MOTOR`)
;

LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaunir\\paraguay.csv" INTO TABLE noschema.flota
FIELDS TERMINATED BY ","
ENCLOSED BY '"'
LINES TERMINATED BY "\r\n"
IGNORE 1 LINES
(`MERCADO`,
`SEGMENTO`,
`MARCA`,
`MGEN`,
`MODELO`,
`COLUMNA REFERENCIA`,
`VERSION (SALES DESCRIPTION)`,
`AÑO`,
`MOTOR`,
`CANTIDAD`,
`ORIGEN`,
`SEGMENTO.1`,
`CARROCERIA`,
`TRACCION`,
`CILINDRADA`
)
;
LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaunir\\honduras.csv" INTO TABLE noschema.flota
FIELDS TERMINATED BY ","
ENCLOSED BY '"'
LINES TERMINATED BY "\r\n"
IGNORE 1 LINES
(`MERCADO`,
`SEGMENTO`,
`SEGMENTO.1`,
`MARCA`,
`MGEN`,
`MODELO`,
`COLUMNA REFERENCIA`,
`VERSION (SALES DESCRIPTION)`,
`AÑO`,
`MOTOR`,
`CILINDRADA`,
`COMBUSTIBLE`,
`CANTIDAD`
)
;

LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaunir\\guatemala.csv" INTO TABLE noschema.flota
FIELDS TERMINATED BY ","
ENCLOSED BY '"'
LINES TERMINATED BY "\r\n"
IGNORE 1 LINES
(`MERCADO`,
`SEGMENTO`,
`SEGMENTO.1`,
`MARCA`,
`MGEN`,
`MODELO`,
`COLUMNA REFERENCIA`,
`VERSION (SALES DESCRIPTION)`,
`AÑO`,
`MOTOR`,
`CILINDRADA`,
`CANTIDAD`,
`PROVINCIA`,
`LOCALIDAD`
);

LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaunir\\elsalvador.csv" INTO TABLE noschema.flota
FIELDS TERMINATED BY ","
ENCLOSED BY '"'
LINES TERMINATED BY "\n"
IGNORE 1 LINES
(`MERCADO`,
`SEGMENTO`,
`SEGMENTO.1`,
`MARCA`,
`MGEN`,
`MODELO`,
`COLUMNA REFERENCIA`,
`VERSION (SALES DESCRIPTION)`,
`AÑO`,
`CANTIDAD`,
`NUMERO CHASIS / VIN`,
`MOTOR`,
`NUMERO MOTOR`,
`PROVINCIA`,
`LOCALIDAD`,
`ORIGEN`,
`CILINDRADA`,
`TRACCION`,
`IDENTIFICACION MOTOR`)
    ;
    
LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaunir\\ecuador.csv" INTO TABLE noschema.flota
FIELDS TERMINATED BY ","
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(
`MARCA`,
`COLUMNA REFERENCIA`,
`ORIGEN`,
`AÑO`,
`SEGMENTO`,
`SEGMENTO.1`,
`MOTOR`,
`CILINDRADA`,
`COMBUSTIBLE`,
`LOCALIDAD`,
`PROVINCIA`,
`MERCADO`,
`CANTIDAD`,
`MODELO`,
`VERSION (SALES DESCRIPTION)`,
`MGEN`
)
;

LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaunir\\costa_rica.csv" INTO TABLE noschema.flota
FIELDS TERMINATED BY ","
ENCLOSED BY '"'
LINES TERMINATED BY "\r\n"
IGNORE 1 LINES
(`MERCADO`,
`SEGMENTO`,
`SEGMENTO.1`,
`MARCA`,
`MGEN`,
`MODELO`,
`COLUMNA REFERENCIA`,
`VERSION (SALES DESCRIPTION)`,
`AÑO`,
`ORIGEN`,
`MOTOR`,
`IDENTIFICACION MOTOR`,
`CARROCERIA`,
`CILINDRADA`,
`CILINDROS`,
`DISPOSICION CILINDROS`,
`TRANSMISION`,
`TRACCION`,
`NUMERO CHASIS / VIN`,
`NUMERO MOTOR`,
`DOCUMENTO ORIGEN`,
`CANTIDAD`
)
;

LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaunir\\chile_prt.csv" INTO TABLE noschema.flota
FIELDS TERMINATED BY ","
ENCLOSED BY '"'
LINES TERMINATED BY "\r\n"
IGNORE 1 LINES
(`MERCADO`,
`MARCA`,
`MGEN`,
`MODELO`,
`COLUMNA REFERENCIA`,
`VERSION (SALES DESCRIPTION)`,
`AÑO`,
`MOTOR`,
`NUMERO MOTOR`,
`NUMERO CHASIS / VIN`,
`CANTIDAD`,
`ORIGEN`,
`SEGMENTO`,
`SEGMENTO.1`,
`CARROCERIA`,
`TRACCION`,
`CILINDRADA`,
`IDENTIFICACION MOTOR`
);