SET GLOBAL local_infile = 1;
USE noschema;
LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaunir\\elsalvador.csv" INTO TABLE noschema.flota
FIELDS TERMINATED BY ","
ENCLOSED BY '"'
LINES TERMINATED BY "\n"
IGNORE 1 LINES
(`MERCADO`,
`SEGMENTO`,
`SEGMENTO.1`,
`MARCA`,
`MGEN`,
`MODELO`,
`COLUMNA REFERENCIA`,
`VERSION (SALES DESCRIPTION)`,
`AÑO`,
`CANTIDAD`,
`NUMERO CHASIS / VIN`,
`MOTOR`,
`NUMERO MOTOR`,
`PROVINCIA`,
`LOCALIDAD`,
`ORIGEN`,
`CILINDRADA`,
`TRACCION`)
    ;
