SET GLOBAL local_infile = 1;
USE noschema;
LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaunir\\ecuador.csv" INTO TABLE noschema.flota
FIELDS TERMINATED BY ","
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(
`MARCA`,
`COLUMNA REFERENCIA`,
`ORIGEN`,
`AÑO`,
`SEGMENTO`,
`SEGMENTO.1`,
`MOTOR`,
`CILINDRADA`,
`COMBUSTIBLE`,
`LOCALIDAD`,
`PROVINCIA`,
`MERCADO`,
`CANTIDAD`,
`MODELO`,
`VERSION (SALES DESCRIPTION)`,
`MGEN`
)
