SET GLOBAL local_infile = 1;
USE peruoriginal;
LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaunir\\peruoriginal.csv" INTO TABLE peruoriginal.peruoriginal
FIELDS TERMINATED BY ","
ENCLOSED BY '"'
LINES TERMINATED BY "\r\n"
IGNORE 1 LINES
(`DESCRIPCION COMERCIAL 1`,
`DESCRIPCION COMERCIAL 2`,
`DESCRIPCION COMERCIAL 3`,
`DESCRIPCION COMERCIAL 4`,
`DESCRIPCION COMERCIAL 5`,
`ORIGEN`,
`DATOS PERSONALES`,
`FECHA DE IMPORTACION`,
`CANTIDAD`,
`AÑO`,
`MERCADO`,
`MODELO`,
`TIPO_VEHICULO`,
`SEGMENTO.1`,
`CARROCERIA`,
`CHASIS`,
`NUMERO MOTOR`,
`TRACCION`,
`CILINDRADA`,
`MOTOR`,
`COMBUSTIBLE`,
`TRANSMISION`,
`MARCA`,
`VERSION`,
`IDENTIFICACION MOTOR`
)
;
