SET GLOBAL local_infile = 1;
USE costarica;
LOAD DATA LOCAL INFILE "D:\\Basededatos\\Limpioparaentregar\\costa_rica.csv" INTO TABLE costarica.originalcostarica
FIELDS TERMINATED BY ","
ENCLOSED BY '"'
LINES TERMINATED BY "\n"
IGNORE 1 LINES
(`IDENTIFICACION DEL VEHICULO`,
`TIPO IDENTIFICACION`,
`CODIGO MARCA`,
`VELOCIDADES`,
`TRANSMISION`,
`TRACCION`,
`TECHO`,
`PUERTAS`,
`Tipo POTENCIA`,
`Posicion Cilindros`,
`PESO BRUTO`,
`Cantidad Pasajeros`,
`Numero Motor`,
`Numero Ejes`,
`MODELO`,
`ESTILO`,
`CODIGO COLOR`,
`CILINDRAJE`,
`CILINDROS`,
`CODIGO CARROCERIA`,
`ANO MODELO`,
`CODIGO CATEGORIA`,
`PARTIDA_AR`,
`CONDICION`,
`Tipo moto`,
`Tiempos`,
`Tipo Cabina`,
`Tipo techo`,
`Color`,
`Cilindrada`,
`carroceria`,
`Codigo Categor`,
`Categoria Vehiculo`,
`tipo combustible`,
`Estado de la Mercancia`,
`Numero Clase`
)
SET	`IDENTIFICACION DEL VEHICULO` = nullif(`IDENTIFICACION DEL VEHICULO` , ''),
`TIPO IDENTIFICACION` = nullif(`TIPO IDENTIFICACION`, ''),
`CODIGO MARCA` = nullif(`CODIGO MARCA`, ''),
`VELOCIDADES` = nullif(`VELOCIDADES` , ''),
`TRANSMISION` = nullif(`TRANSMISION` , ''),
`TRACCION` = nullif(`TRACCION` , ''),
`TECHO` = nullif(`TECHO` , ''),
`PUERTAS` = nullif(`PUERTAS` , ''),
`Tipo POTENCIA` = nullif(`Tipo POTENCIA`, ''),
`Posicion Cilindros` = nullif(`Posicion Cilindros`, ''),
`PESO BRUTO` = nullif(`PESO BRUTO`, ''),
`Cantidad Pasajeros` = nullif(`Cantidad Pasajeros`, ''),
`Numero Motor` = nullif(`Numero Motor`, ''),
`Numero Ejes` = nullif(`Numero Ejes`, ''),
`MODELO` = nullif(`MODELO` , ''),
`ESTILO` = nullif(`ESTILO` , ''),
`CODIGO COLOR` = nullif(`CODIGO COLOR`, ''),
`CILINDRAJE` = nullif(`CILINDRAJE` , ''),
`CILINDROS` = nullif(`CILINDROS` , ''),
`CODIGO CARROCERIA` = nullif(`CODIGO CARROCERIA`, ''),
`ANO MODELO` = nullif(`ANO MODELO`, ''),
`CODIGO CATEGORIA` = nullif(`CODIGO CATEGORIA`, ''),
`PARTIDA_AR` = nullif(`PARTIDA_AR` , ''),
`CONDICION` = nullif(`CONDICION` , ''),
`Tipo moto` = nullif(`Tipo moto`, ''),
`Tiempos` = nullif(`Tiempos` , ''),
`Tipo Cabina` = nullif(`Tipo Cabina`, ''),
`Tipo techo` = nullif(`Tipo techo`, ''),
`Color` = nullif(`Color` , ''),
`Cilindrada` = nullif(`Cilindrada` , ''),
`carroceria` = nullif(`carroceria` , ''),
`Codigo Categor` = nullif(`Codigo Categor`, ''),
`Categoria Vehiculo` = nullif(`Categoria Vehiculo`, ''),
`tipo combustible` = nullif(`tipo combustible`, ''),
`Estado de la Mercancia` = nullif(`Estado de la Mercancia` , ''),
`Numero Clase` = nullif(`Numero Clase`, '')
;
